{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgresql.serviceAccountName" . }}
  namespace: {{ include "postgresql.namespace" . }}
  labels:
{{ include "postgresql.labels" . | indent 4 }}
{{- end -}}
