{{- if and (not .Values.admin.existingSecret) .Values.admin.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}-admin
  namespace: {{ include "grafana.namespace" . }}
  labels:
{{ include "grafana.labels" . | indent 4 }}
stringData:
  admin-user: {{ .Values.admin.user | quote }}
  admin-password: {{ .Values.admin.password | quote }}
{{- end -}}
