{{- $pgUser := coalesce .Values.auth.username (dig "postgresql" "user" "" .Values.global) -}}
{{- $pgDatabase := coalesce .Values.auth.database (dig "postgresql" "database" "" .Values.global) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ include "postgresql.namespace" . }}
  labels:
{{ include "postgresql.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "postgresql.selectorLabels" . | indent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
{{ include "postgresql.selectorLabels" . | indent 8 }}
    spec:
      serviceAccountName: {{ include "postgresql.serviceAccountName" . }}
      containers:
        - name: postgresql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "postgresql.fullname" . }}-credentials
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ $pgUser }}
                - -d
                - {{ $pgDatabase }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ $pgUser }}
                - -d
                - {{ $pgDatabase }}
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
{{ if .Values.persistence.enabled }}
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
{{ end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
{{ if .Values.persistence.enabled }}
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: {{ include "postgresql.fullname" . }}
{{ end }}
